# Generated by Django 5.2.2 on 2025-07-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Instagram nomi')),
                ('password', models.CharField(max_length=100, verbose_name='Parol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': 'Instagram foydalanuvchisi',
                'verbose_name_plural': 'Instagram foydalanuvchilari',
            },
        ),
    ]
